Branch002
Poikka001/appbookstore pull request #8
Opened 2023-10-15 09:38 UTC by Poikka001

2023-10-15 14:13 UTC, Rommelua requested changes
PR code is not match the task
![image](https://github.com/Poikka001/appbookstore/assets/20326858/d5a8606a-d97e-4dd7-a423-9d0221a88399)

2023-10-15 14:13 UTC, Rommelua commented on pom.xml
> +  <artifactId>liquibase</artifactId>
Why?

2023-10-18 17:57 UTC, Sanderfuck requested changes

2023-10-18 17:57 UTC, Sanderfuck commented on src/main/java/mate/academy/intro/dto/CreateRequestBookDto.java
>      private String author;
You validate title but not author

2023-10-18 18:33 UTC, kerrrusha approved these changes

2023-10-18 18:33 UTC, kerrrusha commented on src/main/java/mate/academy/intro/dto/CreateRequestBookDto.java
>      private String isbn = "" + new Random().
Strings should be joined using `Joiner.on(',')` as specified in the code review rules.

2023-10-18 18:33 UTC, kerrrusha commented on src/main/java/mate/academy/intro/dto/CreateRequestBookDto.java
> +    @NotNull
The field `title` is not marked as `final`. Consider making it `final` if it is a constant.

2023-10-18 18:33 UTC, kerrrusha commented on src/main/java/mate/academy/intro/dto/CreateRequestBookDto.java
>      private BigDecimal price;
The field `price` is not marked as `final`. Consider making it `final` if it is a constant.

2023-10-18 18:33 UTC, kerrrusha commented on src/main/java/mate/academy/intro/dto/CreateRequestBookDto.java
>      private String author;
The field `author` is not marked as `final`. Consider making it `final` if it is a constant.

2023-10-18 18:33 UTC, kerrrusha commented on src/main/java/mate/academy/intro/exeption/CustomGlobalExceptionHandler.java
> +
redundant blank line

2023-10-19 13:20 UTC, merged